### ISSUE TITLE
"Bust-A-Move 2" Dos/4GW error

### ISSUE THREAD

**Issue by postalesdeamor** [MartyShepard/DOSBox-Optionals#17]
"Bust-A-Move 2" can't load:
![dosbox_000](https://user-images.githubusercontent.com/96334148/153118233-d18a980f-1d28-4184-b8b3-5af71d45f075.png)

Works well with DOSBox 0.74-3 standard.

**Comment by MartyShepard** [comment]
Hello,

I just installed, set to 320x240 and it runs by bam2.exe (all other Resolutions too at 1600x1200). Please post your Config.

![](https://user-images.githubusercontent.com/8560193/153383896-e0f0bf63-86b0-4064-90c9-6a479f74fe63.png)

![](https://user-images.githubusercontent.com/8560193/153383940-ec5c6f22-15ec-499d-95e1-2aa440cd0600.png)

**Comment by postalesdeamor** [comment]
Hi Marty, 

I attach you my config file:
[Bust-A-Move 2 - Arcade Edition.conf.txt](https://github.com/MartyShepard/DOSBox-Optionals/files/8044901/Bust-A-Move.2.-.Arcade.Edition.conf.txt)

Same error at any resolution.

Thanks.

**Comment by MartyShepard** [comment]
Set CutVesaResolutionIndex to 32 solves the problem. To use 1600x1200 increase the SVGA Memory Size to 2+.

Recommend Option

```
[dosbox]
memsvga3                = 2
CutVesaResolutionIndex  = 32
```

**Comment by postalesdeamor** [comment]
Works perfect :)

Thanks.
