### ISSUE TITLE
SFX sounds play faster in Blackthorne in the newest release

### ISSUE THREAD

**Issue by Great-Dragon** [MartyShepard/DOSBox-Optionals#6]
I've just found recently that all SFX sounds play faster and with higher pitch in Blackthorne.
This issue occures in DOSBox.SVN.r4397.Optionals.Build.on.Dec.25.2020.183550 and DOSBox.SVN.r4338.Optionals.Build.on.May.2.2020.002901

The latest release that didn't have the issue was DOSBox.SVN.r4306.Optionals.Build.on.Jan.8.2020.090345

https://user-images.githubusercontent.com/12208533/103550971-53159280-4eb2-11eb-973f-b93b95da0b68.mp4

https://user-images.githubusercontent.com/12208533/103550978-56a91980-4eb2-11eb-8ffc-f922b349a70b.mp4

**Comment by MartyShepard** [comment]
Hello @Great-Dragon 

Setting GoldPlay  = true in the sblaster Config, or use the menu (Right Mouse in the Windowed mode on the Small Icon top-left )

Optional.. in combination  play with this options

GoldPlay.Force
GoldPlay.Stereo 
LimitSampleRates

greetings

**Comment by Great-Dragon** [comment]
Thanks. It has worked.
It looks like I've missed many new features of newer builds because I was updating exe file only keeping cfg file the same.
It's a good idea to run dosbox fresh without any configs so it can generate new cfg file with new features.
